### ISSUE TITLE
Allow multiple operators on the same attribute while filtering

### ISSUE THREAD

**Issue by marcusjanke** [graphiti-api/graphiti#109]
Hey Lee, first of all i need to thank you for this great library! 🥇 thanks for all the effort and time you put into this amazing gem.

My issue is regarding the option to allow multiple operators to be used for filtering on a single attribute. We have the use case, that we have an attribute `:date` and we want to filter all Resources where this date is between a given range of dates. 

I know that i could achieve this, by defining my own custom filter for that, but i'm wondering why it is not supported to do something like 

`MyResource.all({filter: {date: { gte: Date.today, lte: Date.today+2.months }}})` ?

In the code 
https://github.com/graphiti-api/graphiti/blob/fc35e6fe0b9865320390e8c3fe9ceb946fed333c/lib/graphiti/scoping/filter.rb#L82 you are using only the first operator and the corresponding value. Is there any reason why you did it like that and not use all passed operators and values? 

If this would be possible, sure it would allow ambiguous requests to filter for example the same attribute on `eq` and `not_eq` with the same value, which would be kind of stupid.

Would appreciate any help on this topic. If you want, i can also prepare a PR to make this possible.
Best regards 😊 🙏

**Comment by richmolj** [comment]
Hey @marcusjanke, thanks ❤️ !

You can achieve what you want with:

```
?filter[date][gte]=<DATE>&filter[date][lte]=<DATE>
```

What you are thinking with a hash `{ gte: <DATE>, lte: <DATE> }` is possible if you wanted to register a [custom type](https://www.graphiti.dev/guides/concepts/resources#custom-types), but it's not how graphiti works by default.

> If this would be possible, sure it would allow ambiguous requests to filter for example the same attribute on eq and not_eq with the same value, which would be kind of stupid.

You can do this with ActiveRecord, too: `Post.where(id: 1).where(id: 2)`. Ultimately I think it would be nonsensical user error more than anything else.

Does that make sense to you?

**Comment by richmolj** [comment]
I see - thanks for the follow-up explanation. I agree looks like a bug, and also that your solution makes sense. Do you want to try for a PR that fixes things by looping? Would be a big help ❤️

**Comment by marcusjanke** [comment]
@richmolj i've created a PR for this.. would love to have your feedback! 
best regards
