### ISSUE TITLE
Support for arbitrary pagination strategy

### ISSUE THREAD

**Issue by dush** [graphiti-api/graphiti#112]
Support use cases where backend either does not support offset or it is expensive operation as in [SQL databases on larger datasets](https://use-the-index-luke.com/sql/partial-results/fetch-next-page)

**Comment by richmolj** [comment]
Hey @dush, sorry for the delay. I think it wouldn't be too implement a cursor pagination strategy, it's just not something I've personally needed. If this is something you'd like to PR for, I'd be happy to walk you through the steps.

**Comment by masterT** [comment]
Is this still relevant?

**Comment by richmolj** [comment]
I think we can close and reopen with a better title if needed. We now support offset and cursors, next best would be stable-id cursors but nobody really asking for that. https://github.com/graphiti-api/graphiti/pull/357
