### ISSUE TITLE
Relationship updates belongs_to record

### ISSUE THREAD

**Issue by alexphys** [graphiti-api/graphiti#12]
Hi, 

I have the following relationship;

```
class OrganizationResource < JsonapiCompliable::Resource
  type :organizations

  model Organization
  
  use_adapter JsonapiCompliable::Adapters::ActiveRecord
....
....
....
  belongs_to :parent, 
    foreign_key: :parent_id,
    scope: -> { Organization.all },
    resource: OrganizationResource
```

When trying to create a new record; 

> Strong Resources

```
StrongResources.configure do
  strong_resource :organization do
    attribute :name, :string

  end
```

> Controller
```
class Api::OrganizationsController < ApiController
  jsonapi resource: OrganizationResource

  strong_resource :organization do
    belongs_to :parent
  end
  before_action :apply_strong_params, only: [:create, :update]

  def create
    organization, success = jsonapi_create.to_a
    if success
        render_jsonapi(organization, scope: false)
      else
        render_errors_for(organization)
    end
  end
```
> Params
```
 {"data"=>
  {"attributes"=>
    {"name"=>"testname",
   ...
   ...
   ...
},
   "relationships"=>{"parent"=>{"data"=>{"type"=>"organizations", "id"=>"1"}}},
   "type"=>"organizations"},
 "action"=>"create",
 "controller"=>"api/organizations"}

```

it will try to update the related parent instead of just using its id for the new record's `parent_id` attribute
and throw any errors that are related with it (such as name can't be blank).

I understand that this is maybe caused because the gem treats all realtionship data as nested associations when deserializing thud trying to update all records inside the relationships value of the params.

Is there a way that I can setup my configuration so this doesn't happen but simply create/update a record with the appropriate relationships?

**Comment by richmolj** [comment]
@alexphys I'm not able to reproduce this. You should end up in the equivalent of

```
the_parent.update_attributes({})
```

Which should have no effect. The `parent_id` should also be present in the child attributes.

If you're getting different behavior, I think I need more code to be able to reproduce.
