### ISSUE TITLE
Add before_validation hook

### ISSUE THREAD

**Issue by richmolj** [graphiti-api/graphiti#122]
Original issue: https://github.com/graphiti-api/graphiti/issues/93

This is helpful to manually add validations that are dependent on the graph, e.g. "the employee must have at least two positions".

**Comment by A-Boudi** [comment]
Hi @richmolj,

I'm interested to work on a PR, I'll be working on this in the weekend. But I'm not sure how I should proceed.

I think that it would be possible to run `before_validation` before `before_commit`. This way all the graph should already be persisted before the validations are run.
