### ISSUE TITLE
Assumed `payload` presence breaks #destroy

### ISSUE THREAD

**Issue by mihaimuntenas** [graphiti-api/graphiti#124]
If the underlying model cannot be destroyed because of validations (eg: ActiveRecord), but rather errors are set, the rendering of :jsonapi_errors fails with:
`ERROR: NoMethodError: undefined method 'relationships' for nil:NilClass`.

This happens because presence of `payload` on the proxy is assumed (which is true for update scenarios), but not for #destroy scenarios.
https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/railtie.rb#L77

A #destroy action requires no additional payload, but rather only the `:id` of the object to be deleted. Thus, the payload is set to `nil`, by the `Base#deserialized_params`
https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/base.rb#L42

@richmolj Any idea which way to fix would be safer/better?
- change `deserialized_params` to return an empty object
- update renderer registration code to permit `nil` payload

**Comment by richmolj** [comment]
Thanks for the well-written issue! ❤️ 

> change deserialized_params to return an empty object

This makes the most sense to me, so we can avoid the conditionals later on.

**Comment by mihaimuntenas** [comment]
@richmolj will be back with a PR.

In the meantime, as a quick fix, one can use the below code in the initialization part of their app,
to replace the railtie code with a patched version:
```ruby
ActiveSupport.on_load(:action_controller) do
  ::ActionController::Renderers.remove(:jsonapi_errors)
  ::ActionController::Renderers.add(:jsonapi_errors) do |proxy, _options|
    self.content_type ||= Mime[:jsonapi]

    validation = GraphitiErrors::Serializers::Validation.new proxy.data, proxy.payload&.relationships

    render json: { errors: validation.errors }, status: :unprocessable_entity
  end
end
```

Note the safe navigation operator on `payload`. Depending on ruby version, this can be replaces with `.try`.

**Comment by mihaimuntenas** [comment]
@richmolj Would you be ok with assuming a default value for the `payload` param of the Deserializer initializer ? (`def initialize(payload = {})`)

https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/deserializer.rb#L48

Asking for a friend 😉 ...

**Comment by richmolj** [comment]
Yes!
