### ISSUE TITLE
Use fast_jsonapi instead of jsonapi-rb

### ISSUE THREAD

**Issue by btir** [graphiti-api/graphiti#132]
Hi
I want to know is there any reason why you don't use fast_jsonapi instead of jsonapi-rb?
It seems fast_jsonapi has better performance in lots of benchmarks than jsonapi-rb.

**Comment by btir** [comment]
Oh seems I misunderstood, Sorry.

**Comment by richmolj** [comment]
Hey @btir - it's a good question! I actually think it would be interesting to swap out `jsonapi-rb` for `fast_jsonapi`. But hasn't happened for three reasons:

* Not a top priority, as jsonapi-rb has pretty good performance already
* Last I looked, `fast_jsonapi` was missing some critical functionality. But I think they may have improved in the year since I last checked.
* Some of the benchmarks are [unclear](https://github.com/Netflix/fast_jsonapi/issues/44) and may [depend on the scenario](https://github.com/Netflix/fast_jsonapi/issues/81), and I haven't had the time to dig deep myself.

All that said, I would love to make the serialization layer swappable. This is on a "longer-term" roadmap unless someone wants to spike it out themselves!

**Comment by btir** [comment]
Hi @richmolj 
Thank you for your answer!
Take look at [fast_jsonapi performance methodology](https://github.com/Netflix/fast_jsonapi/blob/master/performance_methodology.md) for the clarity (doesn't take time more than 2 minutes! ). Benchmark source code Also available [here](https://github.com/Netflix/fast_jsonapi/blob/master/spec/lib/object_serializer_performance_spec.rb). 

Below there's a benchmark that explained [here](https://github.com/Netflix/fast_jsonapi/pull/97#issuecomment-368280378)
```
Serialize to Ruby Hash 25 records
Serializer             Records    Time       Speed Up
Fast serializer        25         0.26 ms
AMS serializer         25         8.58 ms    32.9x ✔
jsonapi-rb serializer  25         0.98 ms    3.77x ✔
jsonapi-serializers    25         1.13 ms    4.35x ✔

Serialize to Ruby Hash 250 records
Serializer             Records    Time       Speed Up
Fast serializer        250        2.32 ms
AMS serializer         250        72.35 ms   31.23x ✔
jsonapi-rb serializer  250        7.85 ms    3.39x ✔
jsonapi-serializers    250        6.75 ms    2.92x ✔

Serialize to Ruby Hash 1000 records
Serializer             Records    Time       Speed Up
Fast serializer        1000       9.08 ms
AMS serializer         1000       291.21 ms  32.09x ✔
jsonapi-rb serializer  1000       32.48 ms   3.58x ✔
jsonapi-serializers    1000       27.5 ms    3.03x ✔

Serialize to Ruby Hash 25 with includes and meta
Serializer             Records    Time       Speed Up
Fast serializer        25         0.59 ms
AMS serializer         25         12.47 ms   20.98x ✘
jsonapi-rb serializer  25         4.06 ms    6.83x ✔
jsonapi-serializers    25         2.92 ms    4.92x ✔

Serialize to Ruby Hash 250 with includes and meta
Serializer             Records    Time       Speed Up
Fast serializer        250        5.49 ms
AMS serializer         250        105.43 ms  19.19x ✘
jsonapi-rb serializer  250        19.7 ms    3.59x ✔
jsonapi-serializers    250        24.73 ms   4.5x ✔

Serialize to Ruby Hash 1000 with includes and meta
Serializer             Records    Time       Speed Up
Fast serializer        1000       22.64 ms
AMS serializer         1000       421.55 ms  18.62x ✘
jsonapi-rb serializer  1000       82.29 ms   3.63x ✔
jsonapi-serializers    1000       93.54 ms   4.13x ✔

Serialize to Ruby Hash 25 with polymorphic has_many
Serializer             Records    Time       Speed Up
Fast serializer        25         0.19 ms
AMS serializer         25         6.99 ms    37.47x ✔
jsonapi-rb serializer  25         0.72 ms    3.86x ✔
jsonapi-serializers    25         0.84 ms    4.48x ✔

Serialize to Ruby Hash 250 with polymorphic has_many
Serializer             Records    Time       Speed Up
Fast serializer        250        1.51 ms
AMS serializer         250        53.04 ms   35.24x ✔
jsonapi-rb serializer  250        5.35 ms    3.55x ✔
jsonapi-serializers    250        3.81 ms    2.53x ✔

Serialize to Ruby Hash 1000 with polymorphic has_many
Serializer             Records    Time       Speed Up
Fast serializer        1000       6.06 ms
AMS serializer         1000       191.03 ms  31.51x ✔
jsonapi-rb serializer  1000       22.43 ms   3.7x ✔
jsonapi-serializers    1000       15.37 ms   2.54x ✔
```
As you can see fast_jsonapi is at least 3.5x faster! This is really great!! Specially for big and complex apps. So if the jsonapi-rb changes with fast_jsonapi (not to make the serialization layer swappable)I think it will be a big improvement.
However the functionality of fast_jsonapi must be checked first!!

**Comment by btir** [comment]
[#44](https://github.com/Netflix/fast_jsonapi/issues/44) and [#81](https://github.com/Netflix/fast_jsonapi/issues/81) that you mentioned above, also confirm performance advantage of fast_jsonrb over jsonapi-rb at the end of conversation!

**Comment by richmolj** [comment]
Great information @btir! I would love to try it out, but again not a top priority for me personally. If you wanted to take a crack at this, I'd be happy to give some pointers.

**Comment by btir** [comment]
Your welcome @richmolj.
I'm just new to ruby and rails ( and software development in fact!! ) and I don't know can I do it or no, but nothing to lose! It's my pleasure working on it :)
