### ISSUE TITLE
Relationship readable flag with guard

### ISSUE THREAD

**Issue by richmolj** [graphiti-api/graphiti#143]
For attributes, you can

```ruby
attribute :foo, :string, readable: :admin?

def admin?
  false
end
```

But this does not work the same for relationships - only `true` and `false` are supported.

**Comment by zeisler** [comment]
[This test](https://github.com/graphiti-api/graphiti/blob/master/spec/serialization_spec.rb#L716) seems relevant, but when I change from `readable: false`  to `readable: true` the test still pass. Maybe I'm missing something here.

**Comment by richmolj** [comment]
@zeisler this was due to a pre-1.0 change that unfortunately kept this specific spec passing. I added the relevant line (`Graphiti.setup!`) to the test to make it work correctly. Sorry about that!
