### ISSUE TITLE
`d` helper from GraphitiSpecHelpers::Sugar truncates uuid

### ISSUE THREAD

**Issue by brandynbennett** [graphiti-api/graphiti#155]
The `d` helper truncates `uuid` id types if you try and map over them, leading to false negatives.

Given resources with ids of 
```
[
  '363c374e-8268-11e9-bc42-526af7764f64', 
  '608ac416-8268-11e9-bc42-526af7764f64'
]
```

```
expect(d.map(&:id)).to eq([
  '363c374e-8268-11e9-bc42-526af7764f64', 
  '608ac416-8268-11e9-bc42-526af7764f64'
])
```
Should pass. 

Right now you get something like `[363, 60]` or some other variant of just the first parts of the uuid.

**Comment by richmolj** [comment]
Id automatically converts to an integer. Try rawid to avoid the conversion

**Comment by brandynbennett** [comment]
Thanks! that worked.
