### ISSUE TITLE
graphiti schema not include singular resource endpoint

### ISSUE THREAD

**Issue by alebacca89** [graphiti-api/graphiti#163]
if I add, for example, a route (and respective controller) that allows me to work on the current user, thi endpoint isn'present in graphiti schema and so there isn't into Vandal UI.
What is the best approach to work with single resources? 
I want to integrate Devise with JWT strategy, and I  want manipulate session, and registration (user create, update,destroy,show) with jsonapi standard, and so with Graphiti. Registration is a singular resource because it operates on the current user.

**Comment by caseyprovost** [comment]
I believe you would need to override the Devise controllers and create your own that use Graphiti's resources.

**Comment by caseyprovost** [comment]
cc @alebacca89

**Comment by richmolj** [comment]
Singular resources might be a separate issue, but maybe check out this sample app for handling authentication https://github.com/graphiti-api/user-account-app-cookbook
