### ISSUE TITLE
Cannot make custom operators for `hash` type

### ISSUE THREAD

**Issue by brandynbennett** [graphiti-api/graphiti#164]
You cannot make custom operators for a filter of `hash` type. They all get coerced to be `eq`. Looks like its happening on this line: https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/scoping/filter.rb#L83
https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/scoping/filter.rb#L131-L133

It may be this is code is trying to support the syntax of `filter[metadata]={ "foo": 100 }` instead of the regular `filter[metadata][eq]={ "foo": 100 }`

If that's the case, perhaps the `=` character should be targeted and supported specifically instead of coercing all other potential operator types to be `eq`

**Comment by caseyprovost** [comment]
I believe this is an intended limitation if memory serves. The idea is to create a filter per requirement. So if you wanted to filter by a hash of things you would instead chain X filters where X is the number of keys in your hash. 

If this doesn't work for your use case could you provide an example of a hash filter that exceeds those capabilities or perhaps requires behavior not matched by chaining filters?

**Comment by caseyprovost** [comment]
cc @brandynbennett ^^

**Comment by richmolj** [comment]
I think this is actually probably a bug. @brandynbennett is correct it's along the lines of defaulting `eq` (which we do for all types). Probably around [here](https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/scoping/filter.rb#L132).

I think the initial premise is it only ever makes sense to do `eq` for hashes (no prefix or greater than, etc), but we should still support custom operators.

@caseyprovost I think your idea is a good first-thought, but sometimes you need to filter on multiple things at once (like "id and type"). So I could imagine a custom operator like "id equals X and type starts with Y".

**Comment by caseyprovost** [comment]
@richmolj that sounds good to me :) I'll dig in as soon as I can.

**Comment by brandynbennett** [comment]
@richmolj that's right. The primary use case I’ve come across is needing to do OR logic between operators. In that scenario chaining filters doesn’t work because there isn’t a way to specify HOW to chain them. 

In my case I wanted results to return if they `match` OR `eq`. I wanted to leverage the already built in functions for those operators and the ideal place to do that is right in the resource file. I wanted the name of this new operator to be meaningful and not clobber the default `eq` behavior.

**Comment by caseyprovost** [comment]
@richmolj Looking at the filtering spec it looks like custom hash schemas are supported via custom types: https://github.com/graphiti-api/graphiti/blob/master/spec/filtering_spec.rb#L120. 

Does it make sense to lean on this for the requested feature?

```ruby
# In the schema
metadata = Dry::Types["hash"].schema(
  field_1: Dry::Types["strict.string"],
  field_2: Dry::Types["strict.string"],
)

# In the types files
Graphiti::Types[:metadata] = {
        params: metadata,
        read: metadata,
        write: metadata,
        kind: "record",
        canonical_name: :hash,
        description: "Metadata",
      }

# in the resource
resource.filter :my_custom_filter, :metadata do
        eq do |scope, hash|
          scope.where(field_1: hash[0][:field_1]).
          .or(scope.where(field_2: hash[0][:field_2]))
        end
      end
```

This would allow the client to do something like:

```
?filter[my_custom_filter][field_1]=test&filter[my_custom_filter][field_2]=prod
```

**Comment by richmolj** [comment]
@caseyprovost I think you have a good thought but custom hash schemas are separate. Regardless of a generic hash, or a specific schema, we should allow custom operators that allow the developer to process the hash however they'd wish.

IOW I think the meat of the issue isn't the custom `metadata` type above, but something other than `eq`.

**Comment by richmolj** [comment]
FWIW I think it has to do with [this line](https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/scoping/filter.rb#L132)

**Comment by caseyprovost** [comment]
@richmolj thanks for that insight. How should the library go about supporting custom operators? Should there be a whitelist somewhere? Also, how do we do that without breaking the default equality behavior?

Super down for helping, pairing, or even writing up a PR if we can find an approach that makes sense.

**Comment by richmolj** [comment]
So we already support custom operators for all other types. [You can see the logic here](https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/scoping/filter.rb#L25-L26). The difficulty with hashes is we don't know if the hash key is part of the input, or is meant to be an operator. But I think we can add logic like "if they have a custom operator matching the given key, don't force the operator to `:eq`.

I'd suggest writing a test for it, then playing with the line above - I'm betting it's not too hard once we have the test. Thanks ❤️ !

**Comment by caseyprovost** [comment]
Awesome! I’ll give this a look over and see what I can do.

**Comment by caseyprovost** [comment]
@richmolj here is the sample params I am thinking about:

```ruby
# approach 1
{
  name: {
    match: 'foo',
    eq: 'bar'
  }
}
```

```ruby
# approach 2
{
  name: {
    match_or_eq: 'foo'
  }
}
```

Does either of these structures look what we want?

**Comment by richmolj** [comment]
I think even that's a little more advanced than what we're looking for (though is a cool longer-term feature). Right now we're just looking for something like:

```
user_input = JSON.stringify({ some: 'hash' })
SomeResource.all({
  filter: { name: { match: user_input } }
})
```

**Comment by richmolj** [comment]
IOW we're operating on the whole hash, not individual keys

**Comment by caseyprovost** [comment]
I see! The hash is what the user/client is providing, not the structure of the filter..interesting! Working on this now. 

So we would want the results to be anything that matches the keys or values in the hash?

**Comment by richmolj** [comment]
Well, we're not trying to build in any default behavior. We just want to make sure if the user defines a custom operator (could be `match` or could be `foobar`) that it is called:

```ruby
filter :my_hash, :hash do
  match do |scope, value|
    puts 'I SHOULD BE CALLED!'
  end
end
```
