### ISSUE TITLE
Make it possible to find out about dirty fields before save using ActiveRecord style methods

### ISSUE THREAD

**Issue by mattgibson** [graphiti-api/graphiti#169]
A small feature request: I was hoping to be able to do this on an update operation:

```
model = MymodelResoure.find(params)
if model.somefield_changed? # <-- NoMethodError
  # Do something
end
```

However, those ActiveRecord-style methods are not present.

Trying to use the model directly like this also fails because `.data()` just does a DB fetch and does not add the to-be-saved attributes before returning it.

```
model = MymodelResoure.find(params).data
if model.somefield_changed? # <-- always false
  # Do something
end

```

It would be great if Graphiti could provide the same sort of methods that ActiveRecord does for `xxx_changed?` etc. https://api.rubyonrails.org/classes/ActiveModel/Dirty.html

**Comment by caseyprovost** [comment]
@mattgibson can you not utilize `before_save` or other AR callbacks effectively for this?

**Comment by mattgibson** [comment]
@caseyprovost In the use case for this code, I wanted to do other stuff first, before calling `.save()`, so that wasn't really what I was after. 

Even if it had been, then I think it would still have been valuable to have the convenience methods in order to keep it DRY. Especially since AR already suggests a familiar interface for it based on the field names.

**Comment by caseyprovost** [comment]
@mattgibson I hear ya. Can you expand on "I wanted to do other stuff first"? I Would love to gather more context and see if maybe there is a way to meet requirements already or if we should just bake this feature into the library.

**Comment by mattgibson** [comment]
As I recall, this was when I needed to validate that other models that were being sideposted were going to be valid based on the changed field's new value. i.e. If I choose config setting A on the main subscription model, then I expect there to be several attached sub-setting models that go with it that conform to business rules. If it's config setting B, then the attached sub-setting models should be either gone or conform to different business rules.

In normal Rails code, I'd use `subscription_model.setting_models.build(setting_model_params)` or `accepts_nested_attributes`, then validation callbacks which would then be able to access the already-associated setting models. However, because Graphiti builds and saves the main model and attached/side-posted models separately, this sort of thing doesn't work.

**Comment by caseyprovost** [comment]
@mattgibson for that kind of thing would it make sense to create a composite resource? You can see a similar idea/concept in form objects: https://johnmaddux.com/2019/09/12/creating-multiple-models-with-form-objects-in-rails.

I think this could give you an interesting way to do "package-based" persistence where you have tightly coupled models.

**Comment by caseyprovost** [comment]
@mattgibson maybe you are looking for `after_graph_persist`. It was added a few months back and should meet the requirements (https://github.com/graphiti-api/graphiti/pull/153/files).

Here is a playful example:

```ruby
after_graph_persist do |model|
  model.validate_sitation_x if model.foo.present?
  model.validate_sitation_y if model.bar.present?
end
```
