### ISSUE TITLE
Limiting writes based on model instance

### ISSUE THREAD

**Issue by ribordy** [graphiti-api/graphiti#171]
Looking at [the documentation](https://www.graphiti.dev/guides/concepts/resources#limiting-behavior), it looks like you can pass a method to `readable` that accepts a `model_instance`. It does not appear that you can do the same for `writable`. Is there an alternative method of limiting writes based on permissions or authorization?

The use case here is that I'd like to enables writes on a resource only to the owner of that resource, i.e.:
```ruby
class ThingResource < ApplicationResource
  attribute :id, :uuid
  attribute :name, :string, writable: :owner?

  def owner?(model_instance)
    model_instance.owner == context.current_user
  end
end

**Comment by caseyprovost** [comment]
@ribordy I believe the way you would go about this is by using a library like [Pundit](https://github.com/varvet/pundit) to perform your authorizations at the object or object attribute level.

**Comment by caseyprovost** [comment]
This will also keep your authorization logic out of your resources, which will make testing and re-use far easier.

**Comment by ribordy** [comment]
Thanks @caseyprovost! I had never heard of Pundit, but this seems like exactly what we're looking for.

Maybe it's worth adding a link to Pundit in the documentation, @richmolj?

**Comment by onerinas** [comment]
Here is another way without using pundit: https://github.com/graphiti-api/graphiti/issues/134#issuecomment-489685910
