### ISSUE TITLE
Assign current_user.id to a resource on create?

### ISSUE THREAD

**Issue by JonCrawford** [graphiti-api/graphiti#18]
So how in the world do you assign the current user from the session when you're creating one of his resources? I've spent a couple hours trying to make it work and am striking out. This should be a wiki page.

**Comment by richmolj** [comment]
Hi John - does https://jsonapi-suite.github.io/jsonapi_suite/how-to-scope-to-current-user explain things? Also, feel free to email richmolj@gmail.com for a slack invite where you can ask questions like this

**Comment by JonCrawford** [comment]
Hey Rich. I guess that makes sense, but the docs could be clearer. Here's what I wound up doing. I do kinda wish the `current_user` was referenced in the controller action for maintainability OR this was a callback instead of overriding the default `create` method. But I can live with this.

```ruby
class EventResource < ApplicationResource
  # [...]

  # Overriding #create method. Would prefer a #before_create callback.
  def create(attributes)
    attributes[:user] = context.send(:current_user)
    super
  end
end
```

**Comment by richmolj** [comment]
I agree the docs could be clearer - a PR to the gh-pages branch is always welcome! 👏 

I typically have `current_user` in my controller, and access like this:

```ruby
# app/controllers/application_controller.rb
def current_user
  # your auth logic
end

# app/resources/application_resource.rb
def current_user
  @context.current_user
end
```

So the final code in your case would end up:

```ruby
def create(attributes)
  attributes[:user] = current_user
  super
end
```

I'm split on the callbacks - I wouldn't turn down a PR, but I'm not totally sold the extra abstraction is worth it.
