### ISSUE TITLE
Can Graphiti generate documentation?

### ISSUE THREAD

**Issue by yjukaku** [graphiti-api/graphiti#180]
Hello again! I'm wondering if Graphiti supports generation of documentation in any way. It doesn't seem to me like anything is built in, but are there any tools that will generate documentation based on a Graphiti implementation?

I understand that Graphiti's resources are _somewhat_ documented via the `schema.json`, and we can use Vandal to inspect what resources are available and what actions on those resources are available. But is there any further way to describe resources and relationships?

For example, if we have a User model, how would an API client know that to add someone as a friend, they should create a UserRelationship with `relation: "friend"`? Anything more than trivial resource retrieval requires prior knowledge of the graph. It'd be nice to be able to describe these types of operations.

I'm just trying to compare our options for building the next version of our API, and we're comparing combinations of JSON-API, Swagger/OpenAPI, and Graphiti.

**Comment by richmolj** [comment]
Hey @yjukaku - we support descriptions of resources and attributes. [Here's an example of doing it inline](https://github.com/graphiti-api/graphiti/blob/master/spec/fixtures/employee_directory.rb#L197-L214) and [here's an example of doing it with a yaml file](https://github.com/graphiti-api/graphiti/blob/d737072540372680178b2bfef05f037e00880638/spec/support/locale/documentation_i18n.yml).

Though this will appear in your schema, nothing in Vandal is taking advantage of it at the moment (though I'd certainly merge a PR 🙂 ).

**Comment by richmolj** [comment]
(also thanks to @wadetandy for adding that functionality) ❤️

**Comment by yjukaku** [comment]
Thanks for your quick response! So I suppose that the Endpoints themselves don't have a way to emit documentation 🤔. Do you think that's something Graphiti could eventually cover? Or is that outside of Graphiti's scope?

For example, describing the side effects of creating a resource, like a welcome email being sent on User creation.

**Comment by richmolj** [comment]
I think it would be pretty straightforward to add endpoint descriptions to the schema, but I'm not sure it's desirable for the use case in question. Imagine saving an `Account` and a `User` in a single request from `/accounts` - the email would still be sent, if it's the `UserResource` doing it.

Resources are 1:1 with an endpoint/action, so you mostly get endpoint documentation with a Resource.

**Comment by caseyprovost** [comment]
@yjukaku I plan to explore this more in the near future. I'd really like to find a way to generate something close to swagger but...prettier :)

**Comment by richmolj** [comment]
If there's further work to do here, let's put in a separate specific issue. Thanks!

**Comment by oboxodo** [comment]
@caseyprovost, I'm interested to know if you ever got to explore this more as you suggested?

**Comment by caseyprovost** [comment]
> @caseyprovost, I'm interested to know if you ever got to explore this more as you suggested?

I wish! I’ve since moved on from the job where this was important. Hopefully I can convince my current company to explore it.
