### ISSUE TITLE
Resource: Custom writes

### ISSUE THREAD

**Issue by JoshNorthrup** [graphiti-api/graphiti#182]
As I'm building out an api against an existing data model I'm finding myself needing to do the following frequently 

```
class CarResource < ApplicationResource
  attribute :color, :string, filterable: true, writable: true
  attribute :user_input_color, :string, :filterable: false, writable: true
end

class CarController < ApplicationController
  include Graphiti::Rails

  def update
    color_param = params[:data][:attributes].extract!(:color)
    params[:data][:attributes].merge!(:user_input_color => color_param[:color]) if color_param.present?

    car = CarResource.find(params)
    ...
  end


  def create
    color_param = params[:data][:attributes].extract!(:color)
    params[:data][:attributes].merge!(:user_input_color => color_param[:color]) if color_param.present?
     ...
  end
end
```

To satisfy an active record callback that would do something similar to
```
class Car < ActiveRecord::Base
  before_save :set_paint_color

  def paint_car
    self.color = self.user_input_color || DEFAULT_PAINT_COLOR
  end
end
```

Ideally I'd like to do something like this to avoid exposing both attributes and keep the behavior uniform when the resource is updated elsewhere (ie relationships)
```
class CarResource < ApplicationResource
  write :color do |value|
    @object.user_input_color = value
  end
end

```

**Comment by richmolj** [comment]
Hey @JoshNorthrup!

If I'm understanding correctly you can use [lifecycle hooks](https://www.graphiti.dev/guides/concepts/resources#persistence-lifecycle-hooks) for this:

```ruby
before_attributes do |attrs|
  attrs[:color] ||= DEFAULT_COLOR
end
```

Does that help?

**Comment by JoshNorthrup** [comment]
Thanks for the quick response @richmolj. 
The AR callbacks already exist so it's something I just have to deal with, not a functionality I'm trying to implement. 

I'd like to expose only the `:color` attribute while defining once how it is actually written to the underlying AR object instead of duplicating this logic in the controllers. Similar to how we can provide a block to `attribute` to customize how it is displayed.

Hopefully that's a bit clearer

**Comment by richmolj** [comment]
So assuming `user_input_color` is an `attr_accessor`, it seems you could

```ruby
before_attributes do |attrs|
  attrs[:user_input_color] = attrs.delete(:color)
end
```

Which would set `user_input_color` on the model instance, as the supplied `color` attribute. I think this is what you're doing in the controllers. Or am I misunderstanding?

**Comment by JoshNorthrup** [comment]
That does work when `user_input_color` is defined on the resource. 
Directly exposing that attribute is what I'm trying to avoid here.

**Comment by JoshNorthrup** [comment]
That does seem to work! I thought I had tried that and the attribute validation was performed after 🤷‍♂ .
Thanks for your help

**Comment by richmolj** [comment]
Awesome, good luck 👍 !
