### ISSUE TITLE
Sideloaded Resource objects are re-used across requests

### ISSUE THREAD

**Issue by zpencerq** [graphiti-api/graphiti#186]
This is a pretty obscure behavior in Graphiti but appears to be a result of the `Sideload` classes memoizing their internal resource instances. These sideload resources are stored on the `Resource` class itself. You can see them in `MyResource.sideloads`.

As a result, if you have any sort of stateful work (memoization) inside your Resource, then it can cause subtle bugs. (Perhaps you wanted to memoize some display logic computation that's shared across fields?)

-------

#### Background
I'm using Graphiti with Pundit roughly as follows:
```ruby
class ApplicationResource < Graphiti::Resource
  include Pundit

  def base_scope
    policy_scope(self.model)
  end

  def current_user
    context.current_user
  end

  # ...
end
```

#### Behavior
I found that users were being resolved with policy_scopes that were based on previous users.

#### Digging
It turns out that Pundit has internal caches for policies and policy_scopes. 
Essentially, whenever `policy_scope(scope)` is called, it will use a standard `||=` memoization strategy to save computation within a request using the `scope` as the key. This cache is an instance variable. (https://github.com/varvet/pundit/blob/master/lib/pundit.rb#L323). 

This odd re-use of `Pundit` objects doesn't occur with standard Controllers or sideload-less Graphiti because these objects are instantiated anew per-request.

#### My work-around

I was able to circumvent this issue in the short term (by completely bypassing Pundit's cache) by using:
```ruby
  def base_scope
    Pundit.policy_scope!(current_user, self.model)
  end
```

An alternative would be to just do `policy_scope(self.model.all)` but that will unnecessarily bloat the Pundit cache of the sideload class (since the cache key would be new every time). 

### Conclusion

Perhaps this bug is outside the scope of Graphiti to deal with, considering it's due in-part to integrating with another library. However, the slight difference in instantiation between non-sideloaded Resources and sideloaded Resources may cause subtle bugs in developer's applications. 

For what it's worth, my expectation of the Resources was that they would be similar to Rails Controllers in that they would be instantiated per-request.

**Comment by richmolj** [comment]
Hey @zpencerq, thanks for the excellent write-up. TBH I hadn't really come across this before - since resources operate on separate model instances, it seems odd you'd want to memoize...but this is a valid edge case, and there are probably others.

I haven't benchmarked but my hunch is we need to keep the resource memoization within a request to avoid extra object allocations. But we need to clear that memoization when the request completes.

One way we could do this is clear them out as part of [with_context](https://github.com/graphiti-api/graphiti/blob/237d388beffa38a62ef93cf58c40608f6e238eb7/lib/graphiti.rb#L34) which is wrapping the request. What do you think?

**Comment by zpencerq** [comment]
My initial thoughts would be to update the location of the sideloaded resources to be on the context itself rather than having a global location for these object instances. (Though I'm not 100% sure that that is inline with what the context is meant for. Maybe there's another object that's providing an execution context.. like the Runner or Query?)

However, I imagine that clearing the sideloaded resources would solve this issue directly. 👍 I'll see about making a PR with this approach.

Honestly, I need to familiarize myself with the implementation more to give better feedback.
