### ISSUE TITLE
Filtering on :id param when using string UUIDs instead of integer IDs

### ISSUE THREAD

**Issue by thomasvds** [graphiti-api/graphiti#192]
First of all, thanks for the wonderful framework 🚀 !

I'm using UUIDs instead of integer IDs on my User model. These UUIDs are still saved in the :id field of that model. I did configure the Types accordingly:
```
Graphiti::Types[:integer_id][:params] = Dry::Types['coercible.string']
Graphiti::Types[:integer_id][:read] = Dry::Types['coercible.string']
Graphiti::Types[:integer_id][:write] = Dry::Types['coercible.string']
```
However I'm faced with a problem that's really driving me mad. In the controller #update action, if I put a `binding.pry` here:
```
module Api
  module V1
    class UsersController < ApplicationController
      def update
        user = UserResource.find(params)
        # binding.pry <<< HERE
        if user.update_attributes
          render jsonapi: user
        else
          render jsonapi_errors: user
        end
      end
    end
  end
end
```
Then the `user` resource is rightly picked from the `id` passed in the params when calling the #update action. However it's ultimately another user that gets updated instead. I can confirm this by looking at the following hook in the `UserResource`:
```
class UserResource < ApplicationResource
  ...attributes ...

  after_attributes do |model|
    # binding.pry <<< HERE
    raise ActionController::BadRequest if model.id != current_user.id
  end
end
```
The user associated with `model` is now different than the one picked in the controller. 

I suspect that this is because of the fact that I'm using `uuid` instead of `id`...Any help would be extremely appreciated :) !

**Comment by richmolj** [comment]
Hey @thomasvds, very sorry for the delay here, somehow fell through the cracks. I think you want the built-in `uuid` type, ie `attribute :id, :uuid`
