### ISSUE TITLE
JSONAPI compliance

### ISSUE THREAD

**Issue by piotrpalek** [graphiti-api/graphiti#201]
Hey, I couldn't find the information elsewhere, sorry if I've missed it. I've got two questions:
1) Is Graphitti aimed to be compliant with JSONAPI?
2) Related, will graphitti support (if it's finished) the official JSONAPI solution for sideposting which for now seems to be https://github.com/json-api/json-api/pull/1254 ?

**Comment by richmolj** [comment]
Hey @piotrpalek !

1. Yes, though we add (compatible) extensions (like filtering, sideposting, etc)
2. I'm not opposed to merging a PR, but I doubt I'd do this work myself. We already have a working solution in sideposting, and it's a minor extension to the spec. I've talking with some JSONAPI folks and it doesn't seem there's much opposition to sideposting, just prohibitively hard and slow to get anything in the spec itself.

**Comment by piotrpalek** [comment]
@richmolj Thanks :)
