### ISSUE TITLE
Question - Multiple level relationship sideposting

### ISSUE THREAD

**Issue by andychongyz** [graphiti-api/graphiti#220]
Hi, first of all, sorry if this is not a good place to ask a question.

From this [example](https://www.graphiti.dev/guides/concepts/resources#expanded-example), it shows how to sidepost for 1 level depth relationship, what if I sidepost from Blog, then to Post, then to Comments, where it has more than 1 nested depth of relationship, is this possible to be done?

**Comment by richmolj** [comment]
Yep, it works the same way - the entities in `included` can have their own `relationships` that correspond with other levels in `included`

**Comment by andychongyz** [comment]
Alright! Thank you!
