### ISSUE TITLE
Polymorphic sideposting undefined method

### ISSUE THREAD

**Issue by andychongyz** [graphiti-api/graphiti#221]
Hi, I was trying to use sideposting to update a polymorphic relationship, and it throws an error saying 
```"#<NoMethodError: undefined method `location' for #<Address:0x00007fedea8e68b0>>"```.

The json request:
```json
{
    "data": {
        "type": "locations",
        "id": 20,
        "attributes": {},
        "relationships": {
            "shop": {
                "data": {
                    "type": "shops",
                    "id": 80,
                    "method": "update"
                }
            },
            "address": {
                "data": {
                    "type": "addresses",
                    "id": 110,
                    "method": "update"
                }
            }
        }
    },
    "included": [
        {
            "type": "shops",
            "id": 80,
            "attributes": {
                "restock_by_default": true
            }
        },
        {
            "type": "addresses",
            "id": 110,
            "attributes": {
                "address1": "testing 321",
                "zip": "1324"
            }
        }
    ]
}
```
The relationship goes like this:
```ruby
class Location < ApplicationRecord
  belongs_to :shop
  has_one :address, as: :addressable, dependent: :destroy
end
```
```ruby
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true
end
```
Does it seem that it is checking if the `address` responds to `location` since I was seeing request to Location resource at the root level?
I was able to fix it by adding the following code to the Address model.
```ruby
def location
    addressable if addressable_type == "Location"
end
```
Is there a better way of doing this? Thank you. 🙏

**Comment by richmolj** [comment]
Hey @andychongyz , I think the most helpful thing would be if you could reproduce this in a spec, want to take a stab at it around [here](https://github.com/graphiti-api/graphiti/blob/master/spec/integration/rails/persistence_spec.rb#L1193)?

**Comment by andychongyz** [comment]
Hi, I figure out that it is because some code in the resource is calling the `location` function. Sorry about that! 🙏
