### ISSUE TITLE
Polymorphic sideposting creating record failed

### ISSUE THREAD

**Issue by andychongyz** [graphiti-api/graphiti#222]
Hi, I encounter this problem 2 months ago, but I forgot to file an issue.

The problem is when I want to create a record that is polymorphically associated, it failed to create due to the address1 presence validation failed, although I did pass in the data.

So, I put a debugger in before_save hook in the AddressResource, and for some reason, the attributes I pass into to create the record went missing.

The relationship: `Location` has one `address`, as: addressable.

Here's the request:
```json
{
    "data": {
        "type": "locations",
        "id": 20,
        "attributes": {},
        "relationships": {
            "shop": {
                "data": {
                    "type": "shops",
                    "id": 80,
                    "method": "update"
                }
            },
            "address": {
                "data": {
                    "type": "addresses",
                    "temp-id": "s0m3uu1d",
                    "method": "create"
                }
            }
        }
    },
    "included": [
        {
            "type": "shops",
            "id": 80,
            "attributes": {
                "restock_by_default": true
            }
        },
        {
            "type": "addresses",
            "temp-id": "s0m3uu1d",
            "attributes": {
                "address1": "testing 33",
                "zip": "13245"
            }
        }
    ]
}
```
Screenshot of attributes went missing:
![image](https://user-images.githubusercontent.com/12697240/78340175-34ebd080-75c8-11ea-831f-d334cf18b6a9.png)

As for now, I will just send a separate POST request to create the Address.

**Comment by richmolj** [comment]
Hey @andychongyz , I think the most helpful thing would be if you could reproduce this in a spec, want to take a stab at it around [here](https://github.com/graphiti-api/graphiti/blob/master/spec/integration/rails/persistence_spec.rb#L1193)?

**Comment by andychongyz** [comment]
@richmolj after poking the spec for a while, and comparing the payload received by the resource through `context`, I found out that the problem is happening due to ActionController automatically converting the all keys from kebab-case(even lowerCamelCase) to snake_case! 😨 Therefore I created a before_action function to transform the key back.

```ruby
def transform_params_for_graphiti!(params)
    clean_temp_id = lambda do |hash|
      hash.transform_keys! do |key|
        ["temp_id", "temp-id", "tempId"].include?(key) ? "temp-id" : key.underscore
      end
      hash.each do |key, value|
        if value.is_a?(ActionController::Parameters)
          clean_temp_id.call(value)
        elsif value.is_a?(Array)
          value.each do |item|
            next unless item.is_a?(ActionController::Parameters)
            clean_temp_id.call(item)
          end
        end
      end
    end
    clean_temp_id.call(params)
  end
```

Btw, why don't we allow the `temp-id` key to be snake_case, `temp_id`? I kind of get it why Rails auto transform the case to snake_case, as it is the naming convention of hash keys in Ruby.
