### ISSUE TITLE
Creating a resource from an ActiveModel object

### ISSUE THREAD

**Issue by ingeniousgenius** [graphiti-api/graphiti#235]
Hey, I was wondering how you're supposed to create say a `current_user_resource` of type `UserResource` from a `User` object that already exists?

I tried calling
```ruby
user_resource = UserResource.new current_user
```

but that does not work.

Specifically, what I'm trying to do is in the `UsersController#create` I want to check if the if the user is logged in already, if so, I want to just return the current_user object with a `not_modified` status.

Else, if the user does not exist, I want to create a new user object. I tried writing it like this also, but it didn't work as there's no `to_jsonapi` method on `<User>`

```ruby
def create
    if current_user.present?
      render jsonapi: current_user, status: :ok
    else
      user = UserResource.build(params)

      if user.save
        render jsonapi: user, status: :created
      else
        render jsonapi_errors: user
      end
    end
  end

**Comment by richmolj** [comment]
Addressed in Slack if I'm not mistaken
