### ISSUE TITLE
gh-pages: Certain outbound links do not work

### ISSUE THREAD

**Issue by happycollision** [graphiti-api/graphiti#25]
(In latest Safari on latest macOS... no idea about others right now)
First of all, just loading the main landing page produces some errors:

![screen shot 2018-01-28 at 5 30 06 pm](https://user-images.githubusercontent.com/3663628/35488659-81d87dfc-0451-11e8-81ae-0e8b3934ca1c.png)

But if I click the link at the center of the page (`jsonapi_spec_helpers`) in the screenshot below, I get the bottom-most error in the console (also pictured in the screenshot), and nothing happens.

![screen shot 2018-01-28 at 5 31 59 pm](https://user-images.githubusercontent.com/3663628/35488680-d80e025a-0451-11e8-95e0-e78eaacceb8d.png)

Same behavior for many—but not all—links throughout the site.

This is an FYI, only. You can right click and open any link in a new tab, no problem.

**Comment by richmolj** [comment]
Yeah, this is a thing with the domain name jsonapi-suite.org. I've actually tried to remove references to this site and point to https://jsonapi-suite.github.io/jsonapi_suite until I get around to fixing it. Thanks for letting me know - where'd you find the link?

**Comment by happycollision** [comment]
Wow. I have no idea how I found that link. Because looking through my
history, I did actually start at the right location. I never realized that
I switched at some point to a different domain.

**Comment by moveson** [comment]
My browser remembers that dead link as well, and it wants to go there every time I type 'jsonapi-suite' in the url bar.
