### ISSUE TITLE
Pagination links are missing any includes for nested associations which have a dot in them

### ISSUE THREAD

**Issue by mattgibson** [graphiti-api/graphiti#260]
Here's my query:

```
https://localhost/deliveries/deliveries?page[page]=1&page[size]=1&include=contents,contents.contents_version.assigner
```

And here's the `next` link from the response:

```
 "next": "https://localhost/deliveries/deliveries?include%5Bcontents%5D%5Bfilter%5D%5Bdelivery_id%5D=5893715&page%5Bnumber%5D=2&page%5Bsize%5D=1"
```

It seems that the second include `contents.contents_version.assigner`, with a dot in it is missing in the link. I've tried now with a few endpoints and it's the same everywhere. Includes with a dot in the are always skipped in the pagination links. The models are just simple `belongs_to`/`has_many` relationships, nothing special.

The use case here is that I am iterating over a large list using `deliveries = deliveries.pages.next` in a `while` loop, so I need to have the sideloads present for each iteration of the loop, not just the first one.

**Comment by richmolj** [comment]
Hey @mattgibson 👋  I don't personally use pagination links and prefer to do this stuff client-side (the link code itself came from community PR). Nothing jumps out to me at a glance but here are the relevant parts of code and tests if you'd like to try your hand at a PR:

https://github.com/graphiti-api/graphiti/blob/fa80b3840377c62091b663df6827a3ffb250991a/lib/graphiti/delegates/pagination.rb#L12-L40
https://github.com/graphiti-api/graphiti/blob/fa80b3840377c62091b663df6827a3ffb250991a/spec/support/pagination_link_helper.rb
https://github.com/graphiti-api/graphiti/blob/4f0b669396518bf5905fee4caff7adc295c92784/spec/rendering_spec.rb#L56-L69

**Comment by mattgibson** [comment]
Hi @richmolj 

Thanks for the pointers. I had a dig into this and it seems to have been fixed in the latest version. No sign of an issue that mentioned it though.
