### ISSUE TITLE
There is a type who can represent a JSON?

### ISSUE THREAD

**Issue by brunoocasali** [graphiti-api/graphiti#263]
Today I'm using a `attribute :my_json_field_at_database, :hash` and it worked nicely until I received an array of hashes.

Then I've got an typecast error (`Graphiti::Errors::TypecastFailed (Class: Failed typecasting ...`).

There is a type who could represent a hash and an array of hashes?

I've checked the https://www.graphiti.dev/guides/concepts/resources#types but can't find a "JSON" type (actually I think the hash was a json like type).  

Thanks in advance 🥇

**Comment by richmolj** [comment]
Hey @brunoocasali - typically we have `array_of_<whatever>` but this [is skipped for hashes](https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/types.rb#L192-L194) as I wasn't sure it made sense, particularly for writes. But that should give you what you need to register your own. Remember you can always create [custom types](https://www.graphiti.dev/guides/concepts/resources#custom-types)

**Comment by brunoocasali** [comment]
Before relying on the setup of a custom type, I solved the issue making the response be always a hash, this way I could avoid the array/object conflict!

If in the future I add a custom type I will post here!

@richmolj thanks for your help! 👍

**Comment by benlieb** [comment]
@brunoocasali did you ever use a custom type for json? I'm trying to figure this out...

**Comment by benlieb** [comment]
@richmolj I think `json` type is common enough (It's a  valid mysql and postgres type to be built in.  What do you think?
