### ISSUE TITLE
Payload does not handle DateTime type as expected

### ISSUE THREAD

**Issue by moveson** [graphiti-api/graphiti#27]
I have registered a Payload type for a simple class:
```
JsonapiSpecHelpers::Payload.register(:course) do
  key(:name, String)
  key(:description, String)
  key(:next_start_time, DateTime)
end
```
And I have written an RSpec test based on the #show template:
```
require 'rails_helper'

RSpec.describe "courses#show", type: :request do
  let(:params) { {} }

  subject(:make_request) { jsonapi_get "/api/v2/courses/#{course.id}", params: params }

  describe 'basic fetch' do
    before { login_as_user }
    let!(:course) { create(:course, description: 'A test course', next_start_time: '2018-07-01 06:00:00') }

    it 'serializes the resource correctly' do
      make_request
      assert_payload(:course, course, json_item)
    end
  end
end
```
When I run the test, the result is:
```
Expected JSON payload key 'next_start_time' to have type DateTime but was String
./spec/controllers/api/v2/courses/show_spec.rb:14:in `block (3 levels) in <main>'
-e:1:in `<main>'
```
I get the same response if I parse the string in advance, like so:
```
let!(:course) { create(:course, description: 'A test course', next_start_time: DateTime.parse('2018-07-01 06:00:00')) }
```
The test passes if I change the registration in the Payload registry to indicate that next_start_time is a String.

I would have expected if a key is registered as `DateTime` in the Payload registry, the test suite would attempt to parse the JSON response string to determine if it was a valid datetime.

**Comment by richmolj** [comment]
I agree with your expected behavior - we should treat `DateTime` as a specially-formatted string and parse it. Probably won't get to this in the near-term but would love to see a PR for it. I think the logic would go [here](https://github.com/jsonapi-suite/jsonapi_spec_helpers/blob/master/lib/jsonapi_spec_helpers/matchers.rb#L22).

**Comment by richmolj** [comment]
Payloads are now gone with Graphiti, and we have better checks for this
