### ISSUE TITLE
Access unsaved model after build?

### ISSUE THREAD

**Issue by ef4** [graphiti-api/graphiti#290]
In a typical `create` endpoint:

```rb
def create
    subscription = SubscriptionResource.build(params)
    if subscription.save
      render jsonapi: subscription, status: 201
    else
      render jsonapi_errors: subscription
    end
  end
end
```

I would like to get my hands on the unsaved model after `build` but before `save`. I can't seem to do this.

If I access `subscription.data`, it ends up resolving an existing record, not my new unsaved one.

It seems that my own model class doesn't get instantiated during `build`, it gets instantiated during `save`.

I'm using a custom non-ActiveRecord resource here with its own adapter that extends the NullAdapter. The only things I've customized on the adapter are `save` and `resolve`.

**Comment by richmolj** [comment]
Would [before_save](https://www.graphiti.dev/guides/concepts/resources#persistence-lifecycle-hooks) work for you? The advantage of doing this in the Resource instead of the controller is the same logic applies even when sideposting.

**Comment by ef4** [comment]
Thanks, yes, that works nicely.
