### ISSUE TITLE
Using Scoped ActiveRecord Associations in Resources ?

### ISSUE THREAD

**Issue by Reizar** [graphiti-api/graphiti#292]
Hi,

First off, thanks for all the hard work on Graphiti, I'm loving it so far! I do have a question though, sorry if I've misunderstood something fundamental here. But still getting my bearings with the library.

I have set up some Associations in my ActiveRecord Models, I'm now trying to expose these through Graphiti.

For example:

```ruby
class Property < ApplicationRecord
  has_many :tenancies, dependent: :destroy
  has_many :renters, through: :tenancies

  has_many :current_tenancies, -> { current }, class_name: 'Tenancy'
  has_many :current_renters, through: :current_tenancies, source: :renter
end

class Tenancy < ApplicationRecord
  belongs_to :renter, class_name: 'User', inverse_of: :tenancies
  belongs_to :property

  scope :current, -> { where('start_date <= ?', Date.today).where('end_date IS NULL OR end_date >= ?', Date.today)}
end
```

I then have my Resources

```ruby
class PropertyResource < ApplicationResource
  self.model = Property
  self.type = :properties
 # ... Attributes defined here

  has_many :tenancies, resource: TenancyResource
  has_many :current_tenancies, resource: TenancyResource
end

class TenancyResource < ApplicationResource
  self.model = Tenancy
  self.type = :tenancies
  # Other attributes here
  attribute :property_id, :integer, only: [:readable, :filterable, :sortable]

  belongs_to :renter, resource: UserResource
  belongs_to :property, resource: PropertyResource

end
```

When I try a request to `/api/v1/properties?include=tenancies`
I get the expected tenancy objects back in the included field.

However when I try `/api/v1/properties?include=current_tenancies` the included field is not present in the response.

Am I doing something wrong here? Do associations have to be redefined in Resources? What would be the correct way to essentially have this scope that I'm after?
( Also, deliberately using a has_many here as I'll soon use a through, as I need fields in the join table )

**Comment by richmolj** [comment]
Hey @Reizar glad you're liking it so far! A good way to think about this is that Graphiti doesn't introspect your activerecord associations, we don't try to automatically apply logic like `has_many :current_tenancies, -> { current }`. This would be fragile and too "magical" for some, and we get some helpful side effects as well.

Instead this would fire the query `TenancyResource.all({ filter: { property_id: 123 })` for both associations by default. What you want to do is customize the params sent to that `.all` query. You could do that like so:

```ruby
has_many :current_tenancies, resource: TenancyResource do
  params do |hash|
    hash[:filter][:current] = true
  end
end
```

Which ends up as ``TenancyResource.all({ filter: { property_id: 123, current: true })`. Now implement that `.current` filter and use your scope:

```ruby
filter :current, :boolean, only: [:eq] do
  eq { |scope| scope.current }
end
```

And you're all good. Some benefits of doing it this way:

* We can automatically generate a Link between resources including this logic
* The `/tenancies` endpoint can now be filtered by `current` standalone without association

See also: https://www.graphiti.dev/tutorial/step_5

**Comment by Reizar** [comment]
@richmolj Thanks for the help and the detailed explanation. That definitely clears things up and I understand how things work now.

However I've tried implementing the code you suggested. ( as well as a different solution where I just added an 'active' column on Tenancy with other logic to control toggling it. So that I don't have to worry about date filtering ). And added in my PropertyResource:
```ruby
has_many :current_tenancies, resource: TenancyResource do
  params do |hash|
    hash[:filter][:current] = true
  end
```
and in my tenancy resource:
```ruby
attribute :active, :boolean
```

However, when I try make a request to `/api/v1/properties?include=current_tenancies` The tenancies are not present in the response, and in the relationships field for a property, it shows:
```json
"relationships": {
  "tenancies": {
      "links": {
          "related": "http://localhost:8000/api/v1/tenancies?filter[property_id]=2"
      }
  },
  "currentTenancies": {
      "links": {
          "related": "http://localhost:8000/api/v1/tenancies?filter[active]=true&filter[property_id]=2"
      }
  }
}
```

So it generates the correct link, but is not including the data in the response. ( visiting the link does provide back the correct data ). Any idea why it might not be included in the response?

**Comment by Reizar** [comment]
Aha, I finally figured this out. Just in case anyone else runs into this in the future, here's what I realized.

I tried changing the name of the association in my Property Resource, when I changed it from "current_tenancies" to "tests", it started working ( with an attr_accessor :tests in my Property model ). So maybe I thought the model association was messing with it somehow. But then when I tried the association name: "active_tenancies" that wouldnt work either. So I realized it was actually the underscored name causing the problem.

I have this in my Application Resource:
```ruby
class CustomSerializer < Graphiti::Serializer
  extend JSONAPI::Serializable::Resource::KeyFormat
  key_format -> (key) { key.to_s.camelize(:lower) }
end

class ApplicationResource < Graphiti::Resource
  # other code
  self.serializer = CustomSerializer
end
```

In order to transform response keys to camelCase. Once i disabled that, things started working properly. So that was messing with it. I've switched my frontend data lib to be SprayPaint, so that should handle things anyway.
