### ISSUE TITLE
Congratulations and questions.

### ISSUE THREAD

**Issue by frederikhors** [graphiti-api/graphiti#298]
I just found this project and your [amazing post](https://www.graphiti.dev/guides/why) summarizes what I have always thought; the working circumstances of the last few years have led me to switch from JSON:API to GraphQL which I hated more and more every day.

Questions:

1. Is Graphite a Rails-only thing? I have to use [Golang](https://golang.org) in my next project. Can you advise me something?

1. Can your JS Spraypaint library be used with any JSON:API backend? Or does the backend need to adhere to custom specifications?

**Comment by richmolj** [comment]
Hey @frederikhors thanks for the kind words ❤️ 

1. Ruby-only thing. I don't have any Go experience unfortunately, though you can implement JSON:API in any language.

2. Graphiti is purely additive to the JSON:API spec. So you can use SP with any JSON:API backend, but functionality not in the core spec like sideposting and extra fields will not work without a Graphiti backend.

HTH and Good luck!

**Comment by frederikhors** [comment]
Thanks for your answer.

Does Spraypaint have a caching layer and the ability to persist in the browser?

**Comment by frederikhors** [comment]
I wanna use it with Svelte and it's [magic Stores](https://svelte.dev/tutorial/writable-stores).

**Comment by richmolj** [comment]
If you mean localStorage no, though `new Model(attributes)` works so it's fairly simple to do it yourself

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by richmolj** [comment]
Good call @sandstrom 👍
