### ISSUE TITLE
Replacing related objects in many_to_many relationship

### ISSUE THREAD

**Issue by piotrekbator** [graphiti-api/graphiti#299]
So that's weird.

[JSON:API spec section on updating resource relationships](https://jsonapi.org/format/#crud-updating-resource-relationships) clearly states that if a relationship is included the server must completely replace the relationship’s value with the value specified in the request.

At the same time it seems that Graphiti only adds new records to a relationship but doesn't replace them which makes removing records hard or even impossible (at the moment I have no idea I would go about that). I tried doing that on a `many_to_many` relationship.

Let me give you an example:

I have a `Lead` model, a `LeadTag` joined with `has_many` associations through a `LeadTagging` model. On Graphiti's side, I've set up `many_to_many` relationships for the two main resources and omitted the joining resource.

When I have a lead with tags A and B and PATCH the lead including only the identifier for the A tag I would expect that the lead would now only have the A tag associated and the B tag would be removed from the association.
But after such a request, Lead stays unchanged. 
When I PATCH the lead including only a C tag, the C tag is indeed added to the association but at the same tame tags A and B don't get removed. And they should, shouldn't they.

So first of all: is this how you intended for things to work in Graphiti? Have you ignored the spec for a purpuse? Or am I misunderstanding something?
Second of all: how am I supposed to remove records from such associations?

**Comment by richmolj** [comment]
Hi @piotrekbator, we added a single key in order to add a lot more power. Please see https://www.graphiti.dev/guides/concepts/resources#sideposting

**Comment by piotrekbator** [comment]
@richmolj thanks for answering! I've seen this but I've got two problems with that:

1. The way it works now is very different from how the spec defines it. That generates the second problem, where a standard JSON:API client implementation doesn't work:
2. Ember-data serializer as it has no knowledge of objects that have been dissociated so I have no way to include them in the payload and mark them with this special key you're proposing.

No hard feelings there, I'm just a bit surprised after lots of good experiences with your library :)

I guess what I'm looking for here is whether I need to make my own adapter for Graphiti or at least monkeypatch it to make it work according to spec or if there's any official way for that. Or plans to make it.

**Comment by piotrekbator** [comment]
@richmolj I've managed to monkeypatch it so that it works according to spec (replaces the relationship if it's provided in the payload). It's not pretty but it works.

I could try cleaning it up and preparing a PR if you'd like to incorporate this behavior into Graphiti but it wouldn't be backward compatible so that would probably be a problem.

Let me know what you think about this whole problem. Is that even a problem from your perspective?

**Comment by richmolj** [comment]
Sincerely glad you got it working @piotrekbator ! 🎉 

Ideally this would happen in a breaking 2.0 - require the `method` key always, and if not present go with this behavior. But that's a ways off I think.

I think it's a problem that there's expected behavior the spec defines we aren't sticking to. That said, in the 3+ years of doing this you are the first person to bring it up 😄  So not a *big* problem IMO. I think our default is the default most expect, even if technically against spec.

**Comment by richmolj** [comment]
We could also do this prior to 2.0 with a configuration option!

**Comment by piotrekbator** [comment]
@richmolj yeah, configuration option might be a way to go.

It's weird that nobody before had this problem - I have no idea how anyone would get ember and graphiti working together and would I really be the first? :D Maybe there's some way I'm not aware of.

OK. So I'll try polishing it up and then figure out how to make it work alongside the current behavior. But that's when I'll have a bit more time, maybe later in December.

Probably we can close it now and I'll open a PR when I've got something ready.
