### ISSUE TITLE
Docs show unsupported relationship guards

### ISSUE THREAD

**Issue by ef4** [graphiti-api/graphiti#307]
The documentation [here](https://www.graphiti.dev/guides/concepts/resources#customizing-relationships) shows passing of symbols and lambdas to the `readable` and `writable` argument to `belong_to` and `has_many`. But after much poking around, it looks like that feature was reverted because it was implemented incorrectly, and the [corresponding tests](https://github.com/graphiti-api/graphiti/blob/63cd4031a366c52e7b7e981d83e6a125f2931603/spec/sideload_spec.rb#L85-L95) are disabled.

**Comment by richmolj** [comment]
Thanks for the heads up! I have removed these docs. Though we support `readable` and `writable` booleans, you're right the symbols/procs were a community PR that didn't work out.
