### ISSUE TITLE
Serialization doesn't work correctly after changing files

### ISSUE THREAD

**Issue by piotrpalek** [graphiti-api/graphiti#311]
This is somewhat of an esoteric bug, as it doesn't even happen for my colleagues, but it happens for me for some reason. So if this doesn't make sense to be on this repo, please close.

My setup:
Windows 10
Docker for Windows (on WSL2)
WSL2

What's happening is that whenever I change a file (any file), my requests stop respecting the "include" param. I can literally do this:

1. Check my request via postman (it has included resources / relationships)
2. Change any file in my API
3. Check the request again (identical), now the response still works, but is missing the whole "relationships" key in the response, and also has no "included" array.

I know this may not even be related to Graphitti, this issue is a long-shot, but maybe someone had a weird case like this as well :)

**Comment by richmolj** [comment]
Hm, I'd really like to help but haven't heard this one before. It does seem related to rails reloading classes in some fashion, but that's as far as I can get without being able to replicate :/

**Comment by sandstrom** [comment]
I'm doing some issue gardening 🌱🌿 🌷 and came upon this issue. Since it's quite old I just wanted to ask if this is still relevant? If it isn't, maybe we can close this issue?

By closing some old issues we reduce the list of open issues to a more manageable set.

**Comment by dsims** [comment]
+1. I have been restarting my dev server anytime I use my API after a change.
