### ISSUE TITLE
Missing requires ActiveModel::Naming and ActiveSupport::Deprecation

### ISSUE THREAD

**Issue by PChambino** [graphiti-api/graphiti#321]
A recent change (https://github.com/graphiti-api/graphiti/commit/cfd74793d263fd5f3762e5f500eb17fa500f2dac) added ActiveModel as a requirement but it is not a dependency of the gem.

It should be possible to `require 'graphiti'` without any prior requires so it can be used in non-rails projects and other contexts. Below is an irb session trying to require graphiti, it also shows another missing require for ActiveSupport::Deprecation.

The missing deprecation require is an easy one, the active model one probably requires more thought on how that should work and what dependencies the gem should have.

<details>
<summary>irb: require graphiti</summary>

```
irb(main):001:0> require 'graphiti'
Traceback (most recent call last):
        9: from /usr/local/lib/ry/current/bin/irb:23:in `<main>'
        8: from /usr/local/lib/ry/current/bin/irb:23:in `load'
        7: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
        6: from (irb):1
        5: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
        4: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
        3: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require'
        2: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti.rb:15:in `<top (required)>'
        1: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti.rb:16:in `<module:Graphiti>'
NameError (uninitialized constant ActiveSupport::Deprecation)
Did you mean?  ActiveSupport::Duration
irb(main):002:0> require 'active_support/deprecation'
=> true
irb(main):003:0> require 'graphiti'
Traceback (most recent call last):
       13: from /usr/local/lib/ry/current/bin/irb:23:in `<main>'
       12: from /usr/local/lib/ry/current/bin/irb:23:in `load'
       11: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/irb-1.2.6/exe/irb:11:in `<top (required)>'
       10: from (irb):3
        9: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        8: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        7: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti.rb:108:in `<top (required)>'
        6: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        5: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        4: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti/errors.rb:1:in `<top (required)>'
        3: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti/errors.rb:2:in `<module:Graphiti>'
        2: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti/errors.rb:16:in `<module:Errors>'
        1: from /usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti/errors.rb:17:in `<class:NullRelation>'
NameError (uninitialized constant Graphiti::Errors::NullRelation::ActiveModel)
Did you mean?  ActiveSupport
irb(main):004:0> require 'active_model/naming'
=> true
irb(main):005:0> require 'graphiti'
/usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti.rb:16: warning: already initialized constant Graphiti::DEPRECATOR
/usr/local/lib/ry/rubies/2.7.2/lib/ruby/gems/2.7.0/gems/graphiti-1.2.32/lib/graphiti.rb:16: warning: previous definition of DEPRECATOR was here
=> true
```
</details>

**Comment by PChambino** [comment]
Here is a PR for the active support deprecation missing require: https://github.com/graphiti-api/graphiti/pull/322

I will leave the other one for @richmolj to decide on the direction, e.g. add active model as a dependency and require it, or avoid using it if not defined, or something else.

For more context on our use case, we have a shared library that adds common configuration and helpers to our projects. One of these is a common configuration for `Graphiti::Resource`. When testing this outside of a Rails project, it needs `require 'active_model/naming'` before `require 'graphiti'`.

**Comment by richmolj** [comment]
Thanks @PChambino for the help and excellent write-up ❤️  I've merged the deprecation PR.

For activemodel/naming, give me a little bit. In practice this is a dependency since we rely on it for errors, but conceptually I'd like to keep with "anything matching the activemodel API" rather than activemodel itself. But if it's a pain I will just require it, since in reality I expect that is what all graphiti users are already requiring.

**Comment by richmolj** [comment]
@PChambino it's just a temporary workaround, but in order to get you a fix in the short term, I'd be fine with `extend( ActiveModel::Naming) if defined?(ActiveModel::Naming)` if you'd like to PR. The very specific scenario that class is used shouldn't give you problems.
