### ISSUE TITLE
Propagating extra_fields to related links

### ISSUE THREAD

**Issue by CGA1123** [graphiti-api/graphiti#328]
Current Graphiti won't propagate the `extra_fields` query parameter for nested resources in their related links.

For example, for a request to `http://example.com/books?extra_fields[authors]=biography` the response would contain in `data.relationship.author.links.related` the following URL: `http://example.com/authors/<author_id>` and does not propagate the `extra_fields` parameter to the nested/child resource (i.e. the URL is not `http://example.com/authors/<author_id>?extra_fields[authors]=biography`).

This is a feature which we are currently implementing by setting the `params_proc` on relationships along with the following monkey-patch on `Resource#around_scoping`:
```ruby
Graphiti::Resource.prepend(Module do
  def around_scoping(scope, query_hash)
    if (extra_fields = query_hash.dig(:extra_fields, type))
      query_hash[:extra_fields][type] = extra_fields.split(',') unless extra_fields.is_a?(Array)
    end

    super(scope, query_hash)
  end
end)
```

The monkey-patch is required in order to avoid serialising `extra_fields` as array query parameters in `Util::Link#raw_url` (i.e. encoding as `extra_fields[resource][]=a&extra_fields[resource][]=b` rather than `extra_fields[resource]=a,b`.

Is there scope for making propagation of `extra_fields` a part of the default propagated parameters for links?
Potential within `Util::Link#params` in the same way the `:filter` is propagated?

**Comment by richmolj** [comment]
Hey @CGA1123! Thanks for the excellent write-up. This is a really interesting use case that to be honest I hadn't thought about before - but would definitely like to support. I think your last sentence is correct if you'd like to try your hand at a PR ❤️
