### ISSUE TITLE
extra_attribute broken in 1.2.32

### ISSUE THREAD

**Issue by bartoszkopinski** [graphiti-api/graphiti#332]
After upgrading to 1.2.32, extra attributes are returned even without the `extra_fields` parameter present.
Not sure if related but I'm using them with a `readable` attribute.

**Comment by richmolj** [comment]
Thanks for the heads up @bartoszkopinski, I will address this shortly. Is this happening only for `.json` URLs, or for all requests including normal JSON:API?

**Comment by richmolj** [comment]
Actually, I can't replicate this. I'm running the sample app on `1.2.33` and everything works correctly in both formats. We also have specs passing. What can I do to replicate this @bartoszkopinski ?

> Not sure if related but I'm using them with a readable attribute.

I'm not totally sure what this means...I tried `extra_attribute :foo, :string, readable: true` and worked as expected.

**Comment by bartoszkopinski** [comment]
Thanks for checking @richmolj. I noticed the fields appeared in my specs after upgrading to 1.2.32, but are gone when pinned to 1.2.31. I will try to narrow it down.

**Comment by richmolj** [comment]
Fixed in `1.2.38`, see https://github.com/graphiti-api/graphiti/pull/346
