### ISSUE TITLE
Missing "type" field fails confusingly

### ISSUE THREAD

**Issue by ef4** [graphiti-api/graphiti#339]
If a client forgets to include the required `type` field in a JSON:API POST, instead of giving a validation error graphiti treats the payload as empty. 

It looks like the body serializes to empty here:

https://github.com/graphiti-api/graphiti/blob/054685c29d8641388a16787591afec2c62f62244/lib/graphiti/request_validators/validator.rb#L38-L42

It would be much better to error loudly that the request is not valid because it lacks a type. It took me quite a long time to figure out what was happening. 😝

**Comment by richmolj** [comment]
Oof, sorry for the hassle, I quite agree. The linked code is even in a RequestValidator class! Thanks for the heads up @ef4

**Comment by richmolj** [comment]
Fix has been merged, thanks again @ef4 for raising the issue!
