### ISSUE TITLE
Does secondary_endpoint support dynamic fields?

### ISSUE THREAD

**Issue by brunoocasali** [graphiti-api/graphiti#353]
Hi, me again! 😄 

I'm trying to use a resource called `ProfileResource` outside of their main domain (api/v1/profiles), I've added to project something like:

```rb
# routes.rb

    resources :jobs, only: %i[create index show destroy] do
      resources :candidates, only: :index, controller: 'jobs/candidates'
    end

# jobs/candidates/controller

module Jobs
  class CandidatesController < ApplicationController
    def index
      candidates = ProfileResource.all(params)

      respond_with(candidates)
    end
  end
end

class ProfileResource < ApplicationResource
   # does not work
   secondary_endpoint '/jobs/:job_id/candidates', [:index] 

   # does work but clearly is not dynamic!
   secondary_endpoint '/jobs/7cab9181-0599-4ac3-95e8-06ace9010664/candidates', [:index]
   
   ...   
end
```

And I've got this error:
```rb
Graphiti::Errors::InvalidEndpoint (          ProfileResource cannot be called directly from endpoint /api/v1/jobs/7cab9181-0599-4ac3-95e8-06ace9010664/candidates#index!

          Either set a primary endpoint for this resource:

          primary_endpoint '/my/url', [:index, :show, :create]

          Or whitelist a secondary endpoint:

          secondary_endpoint '/my_url', [:index, :update]

          The current endpoints allowed for this resource are: [{:path=>:"/profiles", :full_path=>:"/api/v1/profiles", :url=>:"http://localhost:3000/api/v1/profiles", :actions=>[:index, :show, :create, :update, :destroy]}, {:path=>:"/jobs/:job_id/candidates", :full_path=>:"/api/v1/jobs/:job_id/candidates", ...
```

If this is not supported now, but could be implemented, I would be happy to send a PR to help this work!
But if it was supposed to work, how can I do that?

Thanks for your awesome work! 🙏

**Comment by richmolj** [comment]
You can turn off endpoint validation (`Resource.validate_endpoints = false`) or override `Resource.allow_request?` https://github.com/graphiti-api/graphiti/blob/master/lib/graphiti/resource/links.rb#L71

But these nested routes are not the happy path when using Graphiti, which prefers a flat graph that is easier to reason about. Instead consider `/candidates?filter[job_id]=123`

**Comment by deyemiobaa** [comment]
Hi @brunoocasali. I ran into this same problem today, can you please share the workaround you used?

**Comment by brunoocasali** [comment]
Hi @deyemiobaa, I left the company I worked with graphiti. But in fact, if I remember correctly, I did what Rich suggested and it works (using `?filter[job_id]=123`)
