### ISSUE TITLE
Pagination links are present on #show endpoints

### ISSUE THREAD

**Issue by richmolj** [graphiti-api/graphiti#356]
When `Graphiti.config.pagination_links = true`

**Comment by richmolj** [comment]
That would be a big help @richmolj , thanks ❤️ !

Start by turning on pagination links with `Graphiti.config.pagination_links = true` in an initializer.

Hitting something like `/posts` should now render links in `meta` like `next/prev`. This is all good. But a show endpoint like `/posts/1` should not render them, because we're not paginating in this case.

**Comment by marcelobarreto** [comment]
Sure, thanks, I'll try it :heart_decoration:

**Comment by marcelobarreto** [comment]
PS.: I liked you were talking to yourself, but I understood it was for me :joy:
