### ISSUE TITLE
Multi-tenant app returns other tenant data in sideload

### ISSUE THREAD

**Issue by mozcomp** [graphiti-api/graphiti#383]
We're using graphiti as an API to access a multi-tenanted app using Apartment, where each request can change the MYSQL schema being used.

It seems that side-loading can include another tenant's data, I assume because of caching.

To use caching in this environment we'd need to include the schema name in the cache, but possibly easier to turn caching off.

Any thoughts?

**Comment by wadetandy** [comment]
Top of my head would be that this could be related to concurrency. If apartment uses `Thread.current` to store the tenant under the hood, then it wouldn't be set while doing sideloads with concurrency enabled. Disable with

```ruby
Graphiti.configure do |config|
  config.concurrency = false
end
```

If that works then things will slow down a bit but your data will stay correct.

**Comment by mozcomp** [comment]
Thanks for the quick reply Wade,
concurrency already set to false

**Comment by richmolj** [comment]
Hard to say with concurrency off...we don't have any other cache in Graphiti so if it's not concurency I'm not sure what is happening. Not familiar with Apartment, sorry :(
