### ISSUE TITLE
Bit confused about releases

### ISSUE THREAD

**Issue by adzap** [graphiti-api/graphiti#385]
Don't mean to be a pain, but I am interested to review the changelog of each gem version released. I'm guilty of falling behind in the changelog of my own gems, but just want to confirm if and where a current changelog might be. 

I see you have github releases but they seem to be outdated and missing the 1.3.x releases. The changelog on master has no version past 1.1.0 and might be accumulating released changes under the 'Unreleased' header. 

Can you please clarify the above for me. 

Thanks

**Comment by richmolj** [comment]
Hi @adzap recent commits have largely been to facilitate upcoming GraphQL work and aren't really helpful past that so it's been less of an issue for me. I'm also just generally falling behind as I focus on GQL. Hopefully this will change in the next couple months.

**Comment by sandstrom** [comment]
I had the same question as OP.

Maybe use an automated generator? I know some people dislike them, but I think they're more than good enough for 95% of cases. Almost no work once they're setup.

https://github.com/github-changelog-generator/github-changelog-generator

(more on this https://www.mokkapps.de/blog/how-to-automatically-generate-a-helpful-changelog-from-your-git-commit-messages/)

**Comment by richmolj** [comment]
Not against it. Mostly let's stick a pin in this for now and revisit in the next 1-2 months please 🙏

**Comment by jkeen** [comment]
@sandstrom Automated releases are wired up and working now. Conventional commits + semantic release 🚀

**Comment by sandstrom** [comment]
@jkeen awesome 🎉
