### ISSUE TITLE
Web site: Image is missing.

### ISSUE THREAD

**Issue by Ben-Fenner** [graphiti-api/graphiti#390]
I have no idea where to report this, so I'm reporting it here.

The installation guide has an image that does not show.

Installation Guide URL: https://www.graphiti.dev/guides/getting-started/installation

What it looks like now:
![image](https://user-images.githubusercontent.com/75506118/137370426-9156970d-659f-4c58-bd35-930c08d70f25.png)

What is should look like:
![image](https://user-images.githubusercontent.com/75506118/137370713-97103a6b-f554-4cd5-8cd0-ee393c946cbf.png)

It seems the image source has since gone offline. Here it is from The Wayback Machine:
https://web.archive.org/web/20181205192518/http://www.urbanphoto.net/blog/wp-content/uploads/2010/03/sfz1.jpg
https://web.archive.org/web/20181205192518if_/http://www.urbanphoto.net/blog/wp-content/uploads/2010/03/sfz1.jpg

Maybe host it locally?

**Comment by Ben-Fenner** [comment]
Oh, I've found contact info on the web site. I've sent an e-mail to `richmolj@gmail.com` with a link to this ticket.
Now if only I could figure out how to get to the Slack channel on my desktop app from the link on the web site...

Edit: I had to use a different browser (ugh) to get Slack to work, and I've left a message in the `general` channel about the issue, and linked here.

Edit 2: I have a response from the e-mail saying it may get addressed this weekend. Cool, cool.

**Comment by Ben-Fenner** [comment]
For kicks I checked to see if this was sorted out today and it looks like it still needs fixing.

**Comment by richmolj** [comment]
Fixed now. thanks!

**Comment by Ben-Fenner** [comment]
That's one way to fix it. 😆️

(I realize now that copyright plays into this.)
