### ISSUE TITLE
Is it possible to structure the raw response like the Vandal JSON preview?

### ISSUE THREAD

**Issue by raghubetina** [graphiti-api/graphiti#395]
Hi all,

I was hoping to teach non-programmers how to consume a Graphiti API with a no-code tool. Since they won't be writing any custom code in the client, it would be _very_ helpful if the API  response had the details of associated objects within the main resource itself — the way that Vandal previews it when you click "View as JSON":

<img width="1648" alt="Screen Shot 2021-11-16 at 10 49 14 AM" src="https://user-images.githubusercontent.com/811217/142028988-e3c61490-f003-4905-9a83-75cf41227b2b.png">

Unfortunately (for our purposes), [the actual JSON:API response](https://ddd-msm-2.herokuapp.com/api/v1/movies/29?include=cast,roles) has the associated data located far away (in `includes`), with only links and IDs directly within `data.relationships`.

<img width="1648" alt="Screen Shot 2021-11-16 at 10 49 40 AM" src="https://user-images.githubusercontent.com/811217/142029331-25651a33-81d9-4c55-a3c5-c86590c6a791.png">

I'm trying to figure out how to customize the response to look the way it does within Vandal's "View as JSON" preview; i.e., with each associated object's details within `data.relationships`, rather than separately in `includes`. I assume that Vandal is doing it client-side?

So far I think I may have to modify [renderer.rb](https://github.com/graphiti-api/graphiti/blob/0389e50f408fdf1c53c17e08ad9e735281b19626/lib/graphiti/renderer.rb). If not, I was hoping someone could point me in the right direction.

Thank you!

**Comment by richmolj** [comment]
You should get this out of the box if you add `.json` to the url

**Comment by raghubetina** [comment]
@richmolj That's good to know! It works for a resource by itself, but I can't seem to get it working when relationships are included (because it's interpreting the `.json` as another relationship to include, I think).

For example, in [the sample application](https://github.com/graphiti-api/employee_directory), visiting [/api/v1/departments/1?include=teams.json](http://localhost:3000/api/v1/departments/1?include=teams.json) produces an `Graphiti::Errors::InvalidInclude`, 'The requested included relationship "json" is not supported.'

I tried adding some arbitrary parameters after `include` but haven't gotten a working solution yet. Would appreciate any advice!

**Comment by richmolj** [comment]
`.json` comes before the ?

**Comment by raghubetina** [comment]
🤦🏾‍♂️ thank you!
