### ISSUE TITLE
Web site: Hyperlink is broken.

### ISSUE THREAD

**Issue by Ben-Fenner** [graphiti-api/graphiti#396]
On the Quickstart page ( https://www.graphiti.dev/quickstart ) right above the `Persisting` section is a hyperlink to the `Error Handling Guide` which points to this URL: https://www.graphiti.dev/guides/error-handling
That URL gives a 404 error.

![image](https://user-images.githubusercontent.com/75506118/143265404-956d8f43-52b9-41a4-85d0-4dcbef632f1c.png)

Following a different link to the `Error Handling Guide` seems to indicate that this is the correct URL: https://www.graphiti.dev/guides/concepts/error-handling

Here they are side-by-side for comparison:
```
Does not exist:  https://www.graphiti.dev/guides/error-handling
The correct URL: https://www.graphiti.dev/guides/concepts/error-handling
```

A quick find/replace across the whole site might be advisable, just in case. Either way, this should be an easy fix. :grin:
(Sorry for not knowing a better place to report errors with the web site.)

**Comment by Ben-Fenner** [comment]
@richmolj - This is probably another one for you.

**Comment by richmolj** [comment]
Fix now, thanks @Ben-Fenner ❤️ !

**Comment by Ben-Fenner** [comment]
So fast! Thank you!
