### ISSUE TITLE
How to call a custom statistic? Documentation unclear.

### ISSUE THREAD

**Issue by Ben-Fenner** [graphiti-api/graphiti#397]
I've created a custom statistic that I'm trying to call, but the documentation on this is unclear.
Documentation: https://www.graphiti.dev/guides/concepts/resources#statistics

The example shows this custom stat:
```ruby
stat rating: [:average] do
  standard_deviation do |scope, attr|
    # your standard deviation code here
  end
end
```

But I'm not sure what hash to pass to the resource to invoke that `standard_deviation` stat, nor what URL would be used to invoke it. There is nothing in the documentation that explains what to do here. Can the docs be updated? Or am I just missing something?

(Not really related, but here is the full story. I'm actually working with Graphiti 1.3.5 because we're still on Rails 4.2. I believe because of this earlier version, I'm running into a bug with the statistics. The default total/count stat provided by Graphiti seems to include full resources into the `meta` hash, instead of the count. So to get around this bug, I'm trying to implement my own custom `count` stat which I've done and it works for URL calls to the API, but doesn't seem to work when instantiating a Resource directly with a hash. So I'm debugging this custom stat, and I'm having all sorts of problems figuring out how and when and why they are triggered...)

**Comment by richmolj** [comment]
Hey @Ben-Fenner sorry for the confusion and sorry I don't have context on the older version / your particular setup. But you should be able to call these just like when you add a custom filter, ie `/posts?stats[rating]=standard_deviation`

**Comment by Ben-Fenner** [comment]
Thank you for the informative reply Lee. That leaves me with one last question out of curiosity.
If that's how the custom stat above is supposed to be called, then what is the `[:average]` for in the stat definition?
Or should it maybe be?
```ruby
stat rating: [:standard_deviation] do
```
or possibly?
```ruby
stat rating: [:average, :standard_deviation] do
```

**Comment by richmolj** [comment]
The array is you opting-in to stats that are already built into the framework...standard_deviation is a custom one

**Comment by Ben-Fenner** [comment]
Oh, I got it. Thanks!

So if I don't want to opt into the built-in framework stat, then I can leave that array empty?
(Because I am actually trying to override the built-in `count` stat after all...)

**Comment by richmolj** [comment]
yup!

**Comment by Ben-Fenner** [comment]
I'm thinking there must be another bug in Graphiti 1.3.5 where stats are processed correctly for URL-based API calls, but making the same calls to the Resource directly by passing a hash is broken:
```ruby
resources = Resource.all({ stats: { total: :count } })
resources.meta # Expecting a hash with a count but getting an empty hash.
```

Heck, it does the same thing with the built-in framework stat. :frowning_face:

**Comment by richmolj** [comment]
I think string/symbol mismatch, see https://github.com/graphiti-api/graphiti/blob/master/spec/stats_spec.rb

**Comment by Ben-Fenner** [comment]
I've been aware that might be an issue, so I've been alternating between symbols and strings for `count`. I forgot to try it with the built-in framework stat just a few minutes ago, but I just tried it now and it's hasn't helped. I'll take a look at the code linked above and see if I can get a clearer picture. :+1:

**Comment by Ben-Fenner** [comment]
This should work I'd think.
It does work when I call it via URL params in a controller test.
I may have to just resort to controller tests for everything. That's what started me down this path. Trying to simplify my tests (using minitest, not RSpec).

```ruby
class MyResource < ApplicationResource
  def base_scope
    MyModel.all
  end

  stat total: [:count] do
    countmyway do |scope, _|
      scope.count
    end
  end
end
```

```ruby
irb> resources = MyResource.all({ stats: { total: 'countmyway' } })
irb> resources.meta # Expecting this hash to contain something but it is empty.
```

**Comment by Ben-Fenner** [comment]
I am not in a position right now to confirm these issues still exist in the latest version, so I'm closing this ticket.
When we eventually move to Rails 5 and beyond (hopefully soon!) I will revisit this and might be back if things still don't work as expected.
But for now, it's time to retire this ticket.
Thanks again Lee for all of the quick and informative help. :+1:
