### ISSUE TITLE
belongs_to relationship without parent should not return link.

### ISSUE THREAD

**Issue by ziggurat** [graphiti-api/graphiti#71]
A belongs_to relationship with a nil parent should not return a link. Currently it returns a link to the index route and that causes a potential loading of all associated resources to be associated with the belongs_to (that should be only one).

Correct behavior should be to return no link and data: null.

**Comment by richmolj** [comment]
@ziggurat do you think you could write a failing spec for this? The tests would be [here](https://github.com/graphiti-api/graphiti/blob/master/spec/serialization_spec.rb#L1193)

**Comment by ziggurat** [comment]
Is this ok @richmolj ?

https://github.com/graphiti-api/graphiti/pull/72
